// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "f25456a6-4b54-44df-985d-b4aad9806f92";
const char DEVICE_LOGIN_NAME[]  = "504ee468-6248-42fe-acb0-d22639d53e04";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPumpChange();

float hum;
float temp;
float soilmoister;
bool pump;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(hum, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soilmoister, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pump, READWRITE, ON_CHANGE, onPumpChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
